apiVersion: apps/v1
kind: Deployment   
metadata:
  name: kubernetes-deployment
  namespace: interns-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: vrindakohli0909/otpapp:v2
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
  namespace: interns-dev
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    

#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
 # name: kong-image
  #namespace: interns-dev
 
#spec:
#  ingressClassName: kong
#  rules:
 # - http:
  #    paths:
   #   - path: /swagger-ui.html
    #    pathType: Prefix
     #   backend:
      #    service:
       #     name: kubernetes-service
        #    port:
         #     number: 8080